<?php

namespace Proxies\__CG__\ZectranetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Sprint extends \ZectranetBundle\Entity\Sprint implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ZectranetBundle\\Entity\\Sprint' . "\0" . 'id', '' . "\0" . 'ZectranetBundle\\Entity\\Sprint' . "\0" . 'name', '' . "\0" . 'ZectranetBundle\\Entity\\Sprint' . "\0" . 'description', '' . "\0" . 'ZectranetBundle\\Entity\\Sprint' . "\0" . 'tasks', '' . "\0" . 'ZectranetBundle\\Entity\\Sprint' . "\0" . 'projectid', '' . "\0" . 'ZectranetBundle\\Entity\\Sprint' . "\0" . 'project', '' . "\0" . 'ZectranetBundle\\Entity\\Sprint' . "\0" . 'statusid', '' . "\0" . 'ZectranetBundle\\Entity\\Sprint' . "\0" . 'status', '' . "\0" . 'ZectranetBundle\\Entity\\Sprint' . "\0" . 'permissions');
        }

        return array('__isInitialized__', '' . "\0" . 'ZectranetBundle\\Entity\\Sprint' . "\0" . 'id', '' . "\0" . 'ZectranetBundle\\Entity\\Sprint' . "\0" . 'name', '' . "\0" . 'ZectranetBundle\\Entity\\Sprint' . "\0" . 'description', '' . "\0" . 'ZectranetBundle\\Entity\\Sprint' . "\0" . 'tasks', '' . "\0" . 'ZectranetBundle\\Entity\\Sprint' . "\0" . 'projectid', '' . "\0" . 'ZectranetBundle\\Entity\\Sprint' . "\0" . 'project', '' . "\0" . 'ZectranetBundle\\Entity\\Sprint' . "\0" . 'statusid', '' . "\0" . 'ZectranetBundle\\Entity\\Sprint' . "\0" . 'status', '' . "\0" . 'ZectranetBundle\\Entity\\Sprint' . "\0" . 'permissions');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Sprint $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatusid($statusid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatusid', array($statusid));

        return parent::setStatusid($statusid);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusid', array());

        return parent::getStatusid();
    }

    /**
     * {@inheritDoc}
     */
    public function addTask(\ZectranetBundle\Entity\Task $tasks)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTask', array($tasks));

        return parent::addTask($tasks);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTask(\ZectranetBundle\Entity\Task $tasks)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTask', array($tasks));

        return parent::removeTask($tasks);
    }

    /**
     * {@inheritDoc}
     */
    public function getTasks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTasks', array());

        return parent::getTasks();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(\ZectranetBundle\Entity\SprintStatus $status = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getInArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInArray', array());

        return parent::getInArray();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjectid($projectid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjectid', array($projectid));

        return parent::setProjectid($projectid);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectid', array());

        return parent::getProjectid();
    }

    /**
     * {@inheritDoc}
     */
    public function setProject(\ZectranetBundle\Entity\Project $project = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProject', array($project));

        return parent::setProject($project);
    }

    /**
     * {@inheritDoc}
     */
    public function getProject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProject', array());

        return parent::getProject();
    }

    /**
     * {@inheritDoc}
     */
    public function addPermission(\ZectranetBundle\Entity\SprintPermissions $permissions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPermission', array($permissions));

        return parent::addPermission($permissions);
    }

    /**
     * {@inheritDoc}
     */
    public function removePermission(\ZectranetBundle\Entity\SprintPermissions $permissions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePermission', array($permissions));

        return parent::removePermission($permissions);
    }

    /**
     * {@inheritDoc}
     */
    public function getPermissions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermissions', array());

        return parent::getPermissions();
    }

}
