<?php

namespace Proxies\__CG__\ZectranetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserSettings extends \ZectranetBundle\Entity\UserSettings implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'id', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'userid', 'user', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'showClosedProjects', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'disableAllOnEmail', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'disableAllOnSite', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgEmailMessageOffice', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgEmailMessageProject', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgEmailMessageEpicStory', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgEmailMessageTask', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgEmailTaskAdded', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgEmailEpicStoryAdded', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgEmailTaskDeleted', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgEmailEpicStoryDeleted', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgSiteMessageOffice', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgSiteMessageProject', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgSiteMessageEpicStory', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgSiteMessageTask', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgSiteTaskAdded', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgSiteEpicStoryAdded', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgSiteTaskDeleted', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgSiteEpicStoryDeleted');
        }

        return array('__isInitialized__', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'id', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'userid', 'user', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'showClosedProjects', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'disableAllOnEmail', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'disableAllOnSite', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgEmailMessageOffice', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgEmailMessageProject', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgEmailMessageEpicStory', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgEmailMessageTask', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgEmailTaskAdded', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgEmailEpicStoryAdded', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgEmailTaskDeleted', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgEmailEpicStoryDeleted', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgSiteMessageOffice', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgSiteMessageProject', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgSiteMessageEpicStory', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgSiteMessageTask', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgSiteTaskAdded', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgSiteEpicStoryAdded', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgSiteTaskDeleted', '' . "\0" . 'ZectranetBundle\\Entity\\UserSettings' . "\0" . 'msgSiteEpicStoryDeleted');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UserSettings $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserid($userid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserid', array($userid));

        return parent::setUserid($userid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserid', array());

        return parent::getUserid();
    }

    /**
     * {@inheritDoc}
     */
    public function setShowClosedProjects($showClosedProjects)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShowClosedProjects', array($showClosedProjects));

        return parent::setShowClosedProjects($showClosedProjects);
    }

    /**
     * {@inheritDoc}
     */
    public function getShowClosedProjects()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowClosedProjects', array());

        return parent::getShowClosedProjects();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisableAllOnEmail($disableAllOnEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisableAllOnEmail', array($disableAllOnEmail));

        return parent::setDisableAllOnEmail($disableAllOnEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisableAllOnEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisableAllOnEmail', array());

        return parent::getDisableAllOnEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisableAllOnSite($disableAllOnSite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisableAllOnSite', array($disableAllOnSite));

        return parent::setDisableAllOnSite($disableAllOnSite);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisableAllOnSite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisableAllOnSite', array());

        return parent::getDisableAllOnSite();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgEmailMessageOffice($msgEmailMessageOffice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgEmailMessageOffice', array($msgEmailMessageOffice));

        return parent::setMsgEmailMessageOffice($msgEmailMessageOffice);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgEmailMessageOffice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgEmailMessageOffice', array());

        return parent::getMsgEmailMessageOffice();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgEmailMessageProject($msgEmailMessageProject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgEmailMessageProject', array($msgEmailMessageProject));

        return parent::setMsgEmailMessageProject($msgEmailMessageProject);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgEmailMessageProject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgEmailMessageProject', array());

        return parent::getMsgEmailMessageProject();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgEmailMessageEpicStory($msgEmailMessageEpicStory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgEmailMessageEpicStory', array($msgEmailMessageEpicStory));

        return parent::setMsgEmailMessageEpicStory($msgEmailMessageEpicStory);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgEmailMessageEpicStory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgEmailMessageEpicStory', array());

        return parent::getMsgEmailMessageEpicStory();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgEmailMessageTask($msgEmailMessageTask)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgEmailMessageTask', array($msgEmailMessageTask));

        return parent::setMsgEmailMessageTask($msgEmailMessageTask);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgEmailMessageTask()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgEmailMessageTask', array());

        return parent::getMsgEmailMessageTask();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgEmailTaskAdded($msgEmailTaskAdded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgEmailTaskAdded', array($msgEmailTaskAdded));

        return parent::setMsgEmailTaskAdded($msgEmailTaskAdded);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgEmailTaskAdded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgEmailTaskAdded', array());

        return parent::getMsgEmailTaskAdded();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgEmailEpicStoryAdded($msgEmailEpicStoryAdded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgEmailEpicStoryAdded', array($msgEmailEpicStoryAdded));

        return parent::setMsgEmailEpicStoryAdded($msgEmailEpicStoryAdded);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgEmailEpicStoryAdded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgEmailEpicStoryAdded', array());

        return parent::getMsgEmailEpicStoryAdded();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgEmailTaskDeleted($msgEmailTaskDeleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgEmailTaskDeleted', array($msgEmailTaskDeleted));

        return parent::setMsgEmailTaskDeleted($msgEmailTaskDeleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgEmailTaskDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgEmailTaskDeleted', array());

        return parent::getMsgEmailTaskDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgEmailEpicStoryDeleted($msgEmailEpicStoryDeleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgEmailEpicStoryDeleted', array($msgEmailEpicStoryDeleted));

        return parent::setMsgEmailEpicStoryDeleted($msgEmailEpicStoryDeleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgEmailEpicStoryDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgEmailEpicStoryDeleted', array());

        return parent::getMsgEmailEpicStoryDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgSiteMessageOffice($msgSiteMessageOffice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgSiteMessageOffice', array($msgSiteMessageOffice));

        return parent::setMsgSiteMessageOffice($msgSiteMessageOffice);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgSiteMessageOffice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgSiteMessageOffice', array());

        return parent::getMsgSiteMessageOffice();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgSiteMessageProject($msgSiteMessageProject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgSiteMessageProject', array($msgSiteMessageProject));

        return parent::setMsgSiteMessageProject($msgSiteMessageProject);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgSiteMessageProject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgSiteMessageProject', array());

        return parent::getMsgSiteMessageProject();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgSiteMessageEpicStory($msgSiteMessageEpicStory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgSiteMessageEpicStory', array($msgSiteMessageEpicStory));

        return parent::setMsgSiteMessageEpicStory($msgSiteMessageEpicStory);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgSiteMessageEpicStory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgSiteMessageEpicStory', array());

        return parent::getMsgSiteMessageEpicStory();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgSiteMessageTask($msgSiteMessageTask)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgSiteMessageTask', array($msgSiteMessageTask));

        return parent::setMsgSiteMessageTask($msgSiteMessageTask);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgSiteMessageTask()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgSiteMessageTask', array());

        return parent::getMsgSiteMessageTask();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgSiteTaskAdded($msgSiteTaskAdded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgSiteTaskAdded', array($msgSiteTaskAdded));

        return parent::setMsgSiteTaskAdded($msgSiteTaskAdded);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgSiteTaskAdded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgSiteTaskAdded', array());

        return parent::getMsgSiteTaskAdded();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgSiteEpicStoryAdded($msgSiteEpicStoryAdded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgSiteEpicStoryAdded', array($msgSiteEpicStoryAdded));

        return parent::setMsgSiteEpicStoryAdded($msgSiteEpicStoryAdded);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgSiteEpicStoryAdded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgSiteEpicStoryAdded', array());

        return parent::getMsgSiteEpicStoryAdded();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgSiteTaskDeleted($msgSiteTaskDeleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgSiteTaskDeleted', array($msgSiteTaskDeleted));

        return parent::setMsgSiteTaskDeleted($msgSiteTaskDeleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgSiteTaskDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgSiteTaskDeleted', array());

        return parent::getMsgSiteTaskDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgSiteEpicStoryDeleted($msgSiteEpicStoryDeleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgSiteEpicStoryDeleted', array($msgSiteEpicStoryDeleted));

        return parent::setMsgSiteEpicStoryDeleted($msgSiteEpicStoryDeleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgSiteEpicStoryDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgSiteEpicStoryDeleted', array());

        return parent::getMsgSiteEpicStoryDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\ZectranetBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

}
