<?php

namespace Proxies\__CG__\ZectranetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OfficeProfile extends \ZectranetBundle\Entity\OfficeProfile implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ZectranetBundle\\Entity\\OfficeProfile' . "\0" . 'id', '' . "\0" . 'ZectranetBundle\\Entity\\OfficeProfile' . "\0" . 'businessName', '' . "\0" . 'ZectranetBundle\\Entity\\OfficeProfile' . "\0" . 'webSiteURL', '' . "\0" . 'ZectranetBundle\\Entity\\OfficeProfile' . "\0" . 'industry', '' . "\0" . 'ZectranetBundle\\Entity\\OfficeProfile' . "\0" . 'description', '' . "\0" . 'ZectranetBundle\\Entity\\OfficeProfile' . "\0" . 'employeeTitles', '' . "\0" . 'ZectranetBundle\\Entity\\OfficeProfile' . "\0" . 'skillsAvailable', '' . "\0" . 'ZectranetBundle\\Entity\\OfficeProfile' . "\0" . 'officeID', '' . "\0" . 'ZectranetBundle\\Entity\\OfficeProfile' . "\0" . 'office');
        }

        return array('__isInitialized__', '' . "\0" . 'ZectranetBundle\\Entity\\OfficeProfile' . "\0" . 'id', '' . "\0" . 'ZectranetBundle\\Entity\\OfficeProfile' . "\0" . 'businessName', '' . "\0" . 'ZectranetBundle\\Entity\\OfficeProfile' . "\0" . 'webSiteURL', '' . "\0" . 'ZectranetBundle\\Entity\\OfficeProfile' . "\0" . 'industry', '' . "\0" . 'ZectranetBundle\\Entity\\OfficeProfile' . "\0" . 'description', '' . "\0" . 'ZectranetBundle\\Entity\\OfficeProfile' . "\0" . 'employeeTitles', '' . "\0" . 'ZectranetBundle\\Entity\\OfficeProfile' . "\0" . 'skillsAvailable', '' . "\0" . 'ZectranetBundle\\Entity\\OfficeProfile' . "\0" . 'officeID', '' . "\0" . 'ZectranetBundle\\Entity\\OfficeProfile' . "\0" . 'office');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OfficeProfile $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBusinessName($businessName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBusinessName', array($businessName));

        return parent::setBusinessName($businessName);
    }

    /**
     * {@inheritDoc}
     */
    public function getBusinessName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBusinessName', array());

        return parent::getBusinessName();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebSiteURL($webSiteURL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebSiteURL', array($webSiteURL));

        return parent::setWebSiteURL($webSiteURL);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebSiteURL()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebSiteURL', array());

        return parent::getWebSiteURL();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndustry($industry)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndustry', array($industry));

        return parent::setIndustry($industry);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndustry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndustry', array());

        return parent::getIndustry();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfficeID($officeID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfficeID', array($officeID));

        return parent::setOfficeID($officeID);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfficeID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfficeID', array());

        return parent::getOfficeID();
    }

    /**
     * {@inheritDoc}
     */
    public function setOffice(\ZectranetBundle\Entity\Office $office = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOffice', array($office));

        return parent::setOffice($office);
    }

    /**
     * {@inheritDoc}
     */
    public function getOffice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffice', array());

        return parent::getOffice();
    }

}
