<?php

namespace Proxies\__CG__\ZectranetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Conversation extends \ZectranetBundle\Entity\Conversation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ZectranetBundle\\Entity\\Conversation' . "\0" . 'id', '' . "\0" . 'ZectranetBundle\\Entity\\Conversation' . "\0" . 'user1ID', '' . "\0" . 'ZectranetBundle\\Entity\\Conversation' . "\0" . 'user1', '' . "\0" . 'ZectranetBundle\\Entity\\Conversation' . "\0" . 'user2ID', '' . "\0" . 'ZectranetBundle\\Entity\\Conversation' . "\0" . 'user2', '' . "\0" . 'ZectranetBundle\\Entity\\Conversation' . "\0" . 'messages');
        }

        return array('__isInitialized__', '' . "\0" . 'ZectranetBundle\\Entity\\Conversation' . "\0" . 'id', '' . "\0" . 'ZectranetBundle\\Entity\\Conversation' . "\0" . 'user1ID', '' . "\0" . 'ZectranetBundle\\Entity\\Conversation' . "\0" . 'user1', '' . "\0" . 'ZectranetBundle\\Entity\\Conversation' . "\0" . 'user2ID', '' . "\0" . 'ZectranetBundle\\Entity\\Conversation' . "\0" . 'user2', '' . "\0" . 'ZectranetBundle\\Entity\\Conversation' . "\0" . 'messages');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Conversation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getInArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInArray', array());

        return parent::getInArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser1ID($user1ID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser1ID', array($user1ID));

        return parent::setUser1ID($user1ID);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser1ID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser1ID', array());

        return parent::getUser1ID();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser2ID($user2ID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser2ID', array($user2ID));

        return parent::setUser2ID($user2ID);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser2ID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser2ID', array());

        return parent::getUser2ID();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser1(\ZectranetBundle\Entity\User $user1 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser1', array($user1));

        return parent::setUser1($user1);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser1', array());

        return parent::getUser1();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser2(\ZectranetBundle\Entity\User $user2 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser2', array($user2));

        return parent::setUser2($user2);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser2', array());

        return parent::getUser2();
    }

    /**
     * {@inheritDoc}
     */
    public function addMessage(\ZectranetBundle\Entity\ConversationMessage $messages)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMessage', array($messages));

        return parent::addMessage($messages);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMessage(\ZectranetBundle\Entity\ConversationMessage $messages)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMessage', array($messages));

        return parent::removeMessage($messages);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessages', array());

        return parent::getMessages();
    }

}
