<?php

namespace Proxies\__CG__\ZectranetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Request extends \ZectranetBundle\Entity\Request implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'id', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'typeid', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'type', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'userid', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'user', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'projectid', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'project', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'HFForumID', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'HFForum', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'QnAForumID', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'QnAForum', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'officeid', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'office', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'taskid', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'task', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'contactID', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'contact', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'message', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'statusID', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'status', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'date');
        }

        return array('__isInitialized__', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'id', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'typeid', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'type', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'userid', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'user', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'projectid', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'project', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'HFForumID', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'HFForum', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'QnAForumID', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'QnAForum', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'officeid', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'office', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'taskid', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'task', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'contactID', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'contact', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'message', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'statusID', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'status', '' . "\0" . 'ZectranetBundle\\Entity\\Request' . "\0" . 'date');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Request $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeid($typeid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeid', array($typeid));

        return parent::setTypeid($typeid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeid', array());

        return parent::getTypeid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserid($userid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserid', array($userid));

        return parent::setUserid($userid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserid', array());

        return parent::getUserid();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjectid($projectid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjectid', array($projectid));

        return parent::setProjectid($projectid);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectid', array());

        return parent::getProjectid();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfficeid($officeid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfficeid', array($officeid));

        return parent::setOfficeid($officeid);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfficeid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfficeid', array());

        return parent::getOfficeid();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(\ZectranetBundle\Entity\RequestType $type = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\ZectranetBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setProject(\ZectranetBundle\Entity\Project $project = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProject', array($project));

        return parent::setProject($project);
    }

    /**
     * {@inheritDoc}
     */
    public function getProject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProject', array());

        return parent::getProject();
    }

    /**
     * {@inheritDoc}
     */
    public function setOffice(\ZectranetBundle\Entity\Office $office = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOffice', array($office));

        return parent::setOffice($office);
    }

    /**
     * {@inheritDoc}
     */
    public function getOffice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffice', array());

        return parent::getOffice();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaskid($taskid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaskid', array($taskid));

        return parent::setTaskid($taskid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaskid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaskid', array());

        return parent::getTaskid();
    }

    /**
     * {@inheritDoc}
     */
    public function setTask(\ZectranetBundle\Entity\Task $task = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTask', array($task));

        return parent::setTask($task);
    }

    /**
     * {@inheritDoc}
     */
    public function getTask()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTask', array());

        return parent::getTask();
    }

    /**
     * {@inheritDoc}
     */
    public function getInArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInArray', array());

        return parent::getInArray();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactID($contactID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactID', array($contactID));

        return parent::setContactID($contactID);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactID', array());

        return parent::getContactID();
    }

    /**
     * {@inheritDoc}
     */
    public function setContact(\ZectranetBundle\Entity\User $contact = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContact', array($contact));

        return parent::setContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContact', array());

        return parent::getContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessage($message)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessage', array($message));

        return parent::setMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessage', array());

        return parent::getMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatusID($statusID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatusID', array($statusID));

        return parent::setStatusID($statusID);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusID', array());

        return parent::getStatusID();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(\ZectranetBundle\Entity\RequestStatus $status = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setHFForumID($hFForumID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHFForumID', array($hFForumID));

        return parent::setHFForumID($hFForumID);
    }

    /**
     * {@inheritDoc}
     */
    public function getHFForumID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHFForumID', array());

        return parent::getHFForumID();
    }

    /**
     * {@inheritDoc}
     */
    public function setQnAForumID($qnAForumID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQnAForumID', array($qnAForumID));

        return parent::setQnAForumID($qnAForumID);
    }

    /**
     * {@inheritDoc}
     */
    public function getQnAForumID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQnAForumID', array());

        return parent::getQnAForumID();
    }

    /**
     * {@inheritDoc}
     */
    public function setHFForum(\ZectranetBundle\Entity\HFForum $hFForum = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHFForum', array($hFForum));

        return parent::setHFForum($hFForum);
    }

    /**
     * {@inheritDoc}
     */
    public function getHFForum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHFForum', array());

        return parent::getHFForum();
    }

    /**
     * {@inheritDoc}
     */
    public function setQnAForum(\ZectranetBundle\Entity\QnAForum $qnAForum = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQnAForum', array($qnAForum));

        return parent::setQnAForum($qnAForum);
    }

    /**
     * {@inheritDoc}
     */
    public function getQnAForum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQnAForum', array());

        return parent::getQnAForum();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

}
